# This action will create minified script and update meta

name: Minify UserScript and Update Meta

on:
  push:
    branches:
      - main
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      script_name: "ThingiversePlus"

    steps:
      - name: "[git] Checkout"
        uses: actions/checkout@v2

      - name: "[git] Git config"
        run: |
          git config user.name QuBIT Bot
          git config user.email workflow@github.com

      - name: "[node] Use Node.js 14"
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: "[node] Install terser"
        run: npm install terser -g

      - name: "[minify] Minify script"
        run: |
          terser src/${{ env.script_name }}.src.user.js \
            --parse bare_returns \
            --compress \
            --mangle \
            --comments "/@.*|==\/?UserScript==/" \
            --output ${{ env.script_name }}.user.js

      - name: "[script] Update meta.js"
        run: |
          awk '/\/\/ ==UserScript==/,/\/\/ ==\/UserScript==/' \
            src/${{ env.script_name }}.src.user.js \
            > ${{ env.script_name }}.meta.js

      - name: "[git] Git add"
        run: git add -A

      - name: "[git] Check if there are changes to commit"
        run: |
          lines=$( git diff --cached | wc -l )
          if [ $lines -gt 0 ]; then
            haschanges=1
          else
            haschanges=0
          fi
          echo "HAS_CHANGES=$haschanges" >> $GITHUB_ENV

      - name: "[git] Git commit"
        run: git commit -m "Updated minified script and meta"
        if: env.HAS_CHANGES == 1

      - name: "[git] Git push"
        run: git push
        if: env.HAS_CHANGES == 1
